java:
  runtime:
    version: 11
server:
  port: 8085

spring:
  datasource:
    url: jdbc:h2:mem:marketplacedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect